### ISSUE TITLE
Compile issues of sfntly on MacOS 10.10

### ISSUE THREAD

**Issue by swernerx** [bramstein/homebrew-webfonttools#3]
Unfortunately installation of sfntly does not seem to work on MacOS 10.10
This is what comes from using verbose mode for "brew install".

Do you have any idea how to fix this? Thanks!

```
==> ant
Buildfile: /private/tmp/sfntly20150415-39386-1ifcpvo/build.xml

compile:
    [mkdir] Created dir: /private/tmp/sfntly20150415-39386-1ifcpvo/build/classes
    [javac] Compiling 200 source files to /private/tmp/sfntly20150415-39386-1ifcpvo/build/classes
    [javac] /private/tmp/sfntly20150415-39386-1ifcpvo/src/com/google/typography/font/sfntly/sample/sfview/OtTableTagger.java:128: cannot find symbol
    [javac] symbol  : class SafeVarargs
    [javac] location: class com.google.typography.font.sfntly.sample.sfview.OtTableTagger
    [javac]   @SafeVarargs
    [javac]    ^
    [javac] Note: /private/tmp/sfntly20150415-39386-1ifcpvo/src/com/google/typography/font/sfntly/sample/sfview/OtTableTagger.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 1 error

BUILD FAILED
/private/tmp/sfntly20150415-39386-1ifcpvo/common.xml:21: Compile failed; see the compiler error output for details.

Total time: 2 seconds
==> Formula
Tap: bramstein/homebrew-webfonttools
Path: /usr/local/Library/Taps/bramstein/homebrew-webfonttools/sfntly.rb
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/Homebrew/homebrew.git
HEAD: 18fa7b2712755bd79ce8a4a1e982d11a626c57a9
Last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: quad-core 64-bit haswell
OS X: 10.10.3-x86_64
Xcode: 6.3
CLT: 6.3.0.0.1.1428348375
Clang: 6.1 build 602
X11: 2.7.7 => /opt/X11
System Ruby: 2.0.0-p481
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/local/opt/ruby/bin/ruby => /usr/local/Cellar/ruby/2.2.1/bin/ruby
Java: 1.6.0_65
==> ENV
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.10
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/4.3:/usr/local/opt/ant/bin:/usr/bin:/bin:/usr/sbin:/sbin

Error: sfntly 239 did not build
Logs:
     /Users/Sebastian/Library/Logs/Homebrew/sfntly/01.ant
```

**Comment by mynetx** [comment]
https://github.com/googlei18n/sfntly/issues/46

**Comment by davelab6** [comment]
```
==> Installing bramstein/webfonttools/sfntly
Warning: Calling 'depends_on :ant' is deprecated!
Use 'depends_on "ant"' instead.
/usr/local/Homebrew/Library/Taps/bramstein/homebrew-webfonttools/sfntly.rb:7:in `<class:Sfntly>'
Please report this to the bramstein/webfonttools tap!

==> Downloading https://github.com/googlei18n/sfntly
######################################################################## 100.0%
Warning: Cannot verify integrity of sfntly-239.com
A checksum was not provided for this resource
For your reference the SHA256 is: 1ce725e7c0e30b5c4ed32a46ee2ffc80a78a91647ff980c5bc52b8b5fb025516
==> ant -f java/build.xml
Last 15 lines from /Users/dcrossland/Library/Logs/Homebrew/sfntly/01.ant:
2018-03-26 14:20:21 -0400

ant
-f
java/build.xml

Picked up _JAVA_OPTIONS:  -Duser.home=/Users/dcrossland/Library/Caches/Homebrew/java_cache
Buildfile: java/build.xml does not exist!
Build failed

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/bramstein/homebrew-webfonttools/issues

These open issues may also help:
Update sfntly.rb https://github.com/bramstein/homebrew-webfonttools/pull/23
Compile issues of sfntly on MacOS 10.10 https://github.com/bramstein/homebrew-webfonttools/issues/
```
